# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pims_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=pims_admin
spring.datasource.password=PimsPassword123!

# Ensure Flyway uses the same credentials
spring.flyway.user=pims_admin
spring.flyway.password=PimsPassword123!

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Migration Settings
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.main.allow-bean-definition-overriding=true