# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/prison_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=YOUR_MYSQL_PASSWORD

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Migration Settings
spring.flyway.enabled=true